### ISSUE TITLE
Multiline quote support

### ISSUE THREAD

**Issue by kovasap** [flwyd/vim-conjoin#1]
I read on vi-users@ mailing list that support is planned for multiline quotes.  Opening this issue to track the work!  I'm happy to help with testing if need be.

**Comment by kovasap** [comment]
From the list:
   
> For multiline quoted strings, it'd also be useful to reflow them like {Visual}gq does for comments.

**Comment by flwyd** [comment]
Initial support for quoted string joining is in.  There are probably a hundred more filetypes that could be added, but I think the initial pass is a good start.

There are some corner cases that could be handled better; in particular, I don't think the following quotes should get merged:
```python
"""Tripple double quotes"""
"Single double quotes"

r'raw string'
'normal string'
```
particularly since `'normal string' r'raw string'` won't be joined.  Detecting those situations in the general case will take significantly more work.

Reflowing strings like `gq` does would be interesting, but in the spirit of "Do one thing well" I'm not sure that feature belongs in this plugin.  It kinda feels like something that formatting programs, e.g. `clang-format` should handle, though a vim-settings-aware generic implementation could be attractive as well.

**Comment by kovasap** [comment]
Works great for me, thank you!
